### ISSUE TITLE
Angles are being converted to radians incorrectly

### ISSUE THREAD

**Issue by Imagix** [BlakeTacklind/Tile-Creator#4]
The code currently tries to convert angles to radians without considering the underlying types.  For example: data["angle"] / 180 * math.pi.  The first part "data["angle"] / 180" is an integral division.  Thus if the angle is 90, this results in a value of 0.  Which then gets multiplied by pi, which is still 0.

**Comment by Imagix** [comment]
Ah, wait... is this code assuming Python 3?

**Comment by BlakeTacklind** [comment]
Added to the readme about python 3 requirement. Hopefully that will avoid confusion in the future

**Comment by Imagix** [comment]
Hmm... it's a little more restrictive than that.  The f-strings thing isn't available until Python 3.6
